# Generated by Django 2.2.3 on 2019-07-07 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('ArticleModel', 'Article')
    ]
