# Generated by Django 2.2.1 on 2019-06-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlemodel_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='content_template_name',
            field=models.CharField(default='blog_template', max_length=100),
        ),
    ]
