# Generated by Django 2.2.1 on 2019-06-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlemodel_content_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
