# Generated by Django 2.2.3 on 2019-07-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190712_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content_template_url',
            new_name='markdown_filename',
        ),
    ]
