# Generated by Django 2.2.2 on 2019-07-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190630_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='content_template_name',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='content_template_url',
            field=models.CharField(default='article_template', max_length=100),
        ),
    ]
