# Generated by Django 2.2.3 on 2019-07-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190715_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='markdown_filename',
        ),
    ]
