# Generated by Django 2.2.3 on 2019-07-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttuser',
            name='reference',
            field=models.CharField(default='User Reference', max_length=50),
        ),
    ]
